server:
  port: 8080

spring:
  application:
    name: testTask
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_task_db
    username: user
    password: userpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:/db/migration/schema, classpath:/db/migration/data
    lockRetryCount: 10
